# Case insensitive
# Web subcommand
bind: 8080
IP: 0.0.0.0
TLS: false
Certificate: ""
Key: ""
DisableListing: false
Gzip: true
Oneliners: false
Username: admin
Password: notsecure
root: /tmp
private: /root
promptPassword: false
searchAndReplace: ""

# Run subcommand
List: false
binary: ""
args: ""
